name: Staging deployment

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: apeksha-ih-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: apeksha-ih-ttt-app
  #################################################
    
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
            npm install
            npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@main
        with:
          # Artifact name
          name: webpack artifacts
          # A file, directory or wildcard pattern that describes what to upload
          path: public/
    
  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: webpack artifacts
          # Destination path
          path: public

      - name: create image and store in Packages
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          image-name: ${{env.DOCKER_IMAGE_NAME}}
        
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    name: Deploy app container to Azure
    steps:
     - name: "Login via Azure CLI"
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
     - name: Docker Login
       uses: docker/login-action@v1.9.0
       with:
         # Server address of Docker registry. If not set then will default to Docker Hub
         registry: ${{env.IMAGE_REGISTRY_URL}}
         # Username used to log against the Docker registry
         username: ${{ github.actor }}
         # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.GITHUB_TOKEN }}
         
     
     - name: Azure WebApp
       uses: Azure/webapps-deploy@v2
       with:
        # Name of the Azure Web App
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

        run: |
          az logout
